from __future__ import annotations

from collections.abc import Mapping, Sequence
from dataclasses import replace
from datetime import UTC, datetime
from decimal import Decimal
from math import ceil, floor, fma, frexp, isfinite, ldexp, log10, sqrt
from re import fullmatch
from urllib.parse import urlencode

from .data import (
    API_BASELINES,
    DEFAULT_HOSTING_INPUTS,
    DEMAND_PRESETS,
    FRONTIER_MODELS,
    GKE_NODE_POOLS,
    GKE_SOURCE_URL,
    INDEX_VERSION,
    MODEL_SNAPSHOT,
    MODEL_SOURCE_URL,
    PRICE_SOURCE_URL,
    QUANTIZATIONS,
)
from .models import (
    APIBaseline,
    APIComparison,
    APIMode,
    CostFrame,
    CostPlot,
    FrontierModel,
    GKENodePool,
    HostingEstimate,
    HostingInputs,
    LLMSelfHostingView,
    ModelComparison,
    PlotLine,
    PlotTick,
    PrecisionComparison,
    Quantization,
    SensitivityCell,
    SensitivityRow,
    TaskComparison,
    TaskQuality,
)

# Source-faithful UI copy intentionally uses multiplication signs.
# ruff: noqa: RUF001


MONTHLY_HOURS = 730.0
SECONDS_PER_MONTH = MONTHLY_HOURS * 60 * 60
SECONDS_PER_DAY = 24 * 60 * 60
CLUSTER_HOURLY_USD = 0.10

# Coefficients from Go's pure-float64 math.Log and math.Exp implementations.
# Chart samples use these narrow ports because otherwise libm-level ULP drift
# leaks into the shareable URLs generated by Python.
_GO_LOG_COEFFICIENTS = (
    6.666666666666735130e-01,
    3.999999999940941908e-01,
    2.857142874366239149e-01,
    2.222219843214978396e-01,
    1.818357216161805012e-01,
    1.531383769920937332e-01,
    1.479819860511658591e-01,
)
_GO_AMD64_EXP_COEFFICIENTS = (
    2.4801587301587301587e-05,
    1.9841269841269841270e-04,
    1.3888888888888888889e-03,
    8.3333333333333333333e-03,
    4.1666666666666666667e-02,
    1.6666666666666666667e-01,
    5.0000000000000000000e-01,
    1.0000000000000000000e00,
)
_GO_LN2_HI = 6.93147180369123816490e-01
_GO_LN2_LO = 1.90821492927058770002e-10
_GO_AMD64_LN2_UPPER = 0.69314718055966295651160180568695068359375
_GO_AMD64_LN2_LOWER = 0.28235290563031577122588448175013436025525412068e-12
_GO_AMD64_LOG2E = 1.4426950408889634073599246810018920

type QueryValue = str | Sequence[str]
type Query = Mapping[str, QueryValue]


def _first(query: Query, key: str) -> str | None:
    raw = query.get(key)
    if raw is None:
        return None
    if isinstance(raw, str):
        return raw
    return raw[0] if raw else None


def _go_general(value: float) -> str:
    return format(value, ".6g")


def _parse_choice(
    query: Query,
    key: str,
    fallback: str,
    allowed: frozenset[str],
    validation: list[str],
) -> str:
    raw = _first(query, key)
    if raw is None or raw == "":
        return fallback
    if raw in allowed:
        return raw
    validation.append(f"{key} was not recognized; the default was used")
    return fallback


def _parse_bounded_float(
    query: Query,
    key: str,
    fallback: float,
    minimum: float,
    maximum: float,
    validation: list[str],
) -> float:
    raw = _first(query, key)
    if raw is None or raw == "":
        return fallback
    try:
        if raw.strip() != raw:
            raise ValueError
        value = float(raw)
    except ValueError:
        value = float("nan")
    if not isfinite(value) or value < minimum or value > maximum:
        validation.append(
            f"{key} must be between {_go_general(minimum)} and {_go_general(maximum)}; the default was used",
        )
        return fallback
    return value


def _parse_bounded_int(
    query: Query,
    key: str,
    fallback: int,
    minimum: int,
    maximum: int,
    validation: list[str],
) -> int:
    raw = _first(query, key)
    if raw is None or raw == "":
        return fallback
    try:
        # strconv.Atoi accepts only integer syntax, never decimal-valued floats.
        if fullmatch(r"[+-]?[0-9]+", raw) is None:
            raise ValueError
        value = int(raw, 10)
    except ValueError:
        value = minimum - 1
    if value < minimum or value > maximum:
        validation.append(
            f"{key} must be between {minimum} and {maximum}; the default was used",
        )
        return fallback
    return value


def _apply_demand_preset(
    preset_id: str | None,
    inputs: HostingInputs,
    validation: list[str],
) -> HostingInputs:
    if not preset_id:
        return inputs
    for preset in DEMAND_PRESETS:
        if preset.id == preset_id:
            return replace(
                inputs,
                requests_per_day=preset.requests_per_day,
                active_days=preset.active_days,
                input_tokens_request=preset.input_tokens,
                output_tokens_request=preset.output_tokens,
            )
    validation.append("preset was not recognized; the validated demand inputs were kept")
    return inputs


def _parse_inputs(query: Query) -> tuple[HostingInputs, tuple[str, ...]]:
    validation: list[str] = []
    defaults = DEFAULT_HOSTING_INPUTS
    inputs = replace(
        defaults,
        model_id=_parse_choice(
            query,
            "model",
            defaults.model_id,
            frozenset(model.id for model in FRONTIER_MODELS),
            validation,
        ),
        node_pool_id=_parse_choice(
            query,
            "node",
            defaults.node_pool_id,
            frozenset(node.id for node in GKE_NODE_POOLS),
            validation,
        ),
        quantization_id=_parse_choice(
            query,
            "quant",
            defaults.quantization_id,
            frozenset(quant.id for quant in QUANTIZATIONS),
            validation,
        ),
        replicas=_parse_bounded_int(query, "replicas", defaults.replicas, 1, 8, validation),
        duty_cycle_percent=_parse_bounded_float(
            query,
            "duty",
            defaults.duty_cycle_percent,
            0.1,
            100,
            validation,
        ),
        memory_overhead_pct=_parse_bounded_float(
            query,
            "overhead",
            defaults.memory_overhead_pct,
            0,
            50,
            validation,
        ),
        tokens_per_second=_parse_bounded_float(
            query,
            "throughput",
            defaults.tokens_per_second,
            0.1,
            1_000_000,
            validation,
        ),
        target_utilization=_parse_bounded_float(
            query,
            "utilization",
            defaults.target_utilization,
            1,
            95,
            validation,
        ),
        output_tokens_request=_parse_bounded_float(
            query,
            "tokens",
            defaults.output_tokens_request,
            1,
            1_000_000,
            validation,
        ),
        input_tokens_request=_parse_bounded_float(
            query,
            "input-tokens",
            defaults.input_tokens_request,
            1,
            1_000_000,
            validation,
        ),
        requests_per_day=_parse_bounded_float(
            query,
            "requests",
            defaults.requests_per_day,
            1,
            10_000_000,
            validation,
        ),
        active_days=_parse_bounded_float(
            query,
            "days",
            defaults.active_days,
            1,
            31,
            validation,
        ),
        platform_monthly_usd=_parse_bounded_float(
            query,
            "platform",
            defaults.platform_monthly_usd,
            0,
            10_000_000,
            validation,
        ),
    )
    inputs = _apply_demand_preset(_first(query, "preset"), inputs, validation)
    return _parse_hosting_options(query, inputs, validation), tuple(validation)


def _parse_hosting_options(
    query: Query,
    inputs: HostingInputs,
    validation: list[str],
) -> HostingInputs:
    api_mode = _parse_choice(
        query,
        "api-mode",
        inputs.api_mode.value,
        frozenset(mode.value for mode in APIMode),
        validation,
    )
    inputs = replace(
        inputs,
        api_mode=APIMode(api_mode),
        cache_requests=_parse_bounded_int(
            query,
            "cache-requests",
            inputs.cache_requests,
            1,
            1_000_000,
            validation,
        ),
        concurrency=_parse_bounded_int(
            query,
            "concurrency",
            inputs.concurrency,
            1,
            100_000,
            validation,
        ),
        measured_concurrency=_parse_bounded_int(
            query,
            "measured-concurrency",
            inputs.measured_concurrency,
            0,
            100_000,
            validation,
        ),
    )
    inputs = replace(
        inputs,
        quality_enabled=(
            _parse_choice(
                query,
                "quality",
                "off",
                frozenset(("on", "off")),
                validation,
            )
            == "on"
        ),
    )
    float_fields = (
        ("cache_prefix_tokens", "cache-prefix", 0, 1_000_000),
        ("target_first_token", "target-first", 0.1, 3600),
        ("target_completion", "target-complete", 0.1, 86_400),
        ("measured_first_token", "measured-first", 0, 3600),
        ("measured_completion", "measured-complete", 0, 86_400),
        ("tasks_per_month", "tasks", 1, 10_000_000),
        ("review_hourly_usd", "review-rate", 0, 10_000),
    )
    for attribute, key, minimum, maximum in float_fields:
        inputs = replace(
            inputs,
            **{
                attribute: _parse_bounded_float(
                    query,
                    key,
                    getattr(inputs, attribute),
                    minimum,
                    maximum,
                    validation,
                ),
            },
        )
    qualities: list[TaskQuality] = []
    for index, quality in enumerate(inputs.quality):
        prefix = f"quality-{index}-"
        qualities.append(
            TaskQuality(
                acceptance_percent=_parse_bounded_float(
                    query,
                    prefix + "acceptance",
                    quality.acceptance_percent,
                    0,
                    100,
                    validation,
                ),
                calls_per_task=_parse_bounded_float(
                    query,
                    prefix + "calls",
                    quality.calls_per_task,
                    1,
                    100,
                    validation,
                ),
                review_minutes=_parse_bounded_float(
                    query,
                    prefix + "review",
                    quality.review_minutes,
                    0,
                    480,
                    validation,
                ),
            ),
        )
    quality_0, quality_1, quality_2, quality_3 = qualities
    inputs = replace(inputs, quality=(quality_0, quality_1, quality_2, quality_3))
    if (
        inputs.measured_first_token > 0
        and inputs.measured_completion > 0
        and inputs.measured_first_token > inputs.measured_completion
    ):
        validation.append(
            "Recorded first-token time cannot exceed completion time; both measurements were cleared",
        )
        inputs = replace(inputs, measured_first_token=0, measured_completion=0)
    return inputs


def _find_model(model_id: str) -> FrontierModel:
    return next((model for model in FRONTIER_MODELS if model.id == model_id), FRONTIER_MODELS[0])


def _find_node_pool(node_id: str) -> GKENodePool:
    return next((node for node in GKE_NODE_POOLS if node.id == node_id), GKE_NODE_POOLS[0])


def _find_quantization(quantization_id: str) -> Quantization:
    return next(
        (item for item in QUANTIZATIONS if item.id == quantization_id),
        QUANTIZATIONS[0],
    )


def estimate_hosting(
    model: FrontierModel,
    node: GKENodePool,
    quantization: Quantization,
    inputs: HostingInputs,
) -> HostingEstimate:
    weight_memory = model.parameters_b * quantization.bytes_per_param
    required_memory = weight_memory * (1 + inputs.memory_overhead_pct / 100)
    nodes_per_replica = max(1, ceil(required_memory / node.hbm_gb))
    total_nodes = nodes_per_replica * inputs.replicas
    duty = inputs.duty_cycle_percent / 100
    # Stopping a committed VM reduces serving time, never the contractual bill.
    paid_duty = 1 if node.committed else duty
    compute_monthly = total_nodes * node.hourly_usd * MONTHLY_HOURS * paid_duty
    control_monthly = CLUSTER_HOURLY_USD * MONTHLY_HOURS
    total_monthly = compute_monthly + control_monthly + inputs.platform_monthly_usd
    capacity = inputs.tokens_per_second * inputs.replicas * (inputs.target_utilization / 100) * SECONDS_PER_MONTH * duty
    capacity_requests_day = (
        inputs.tokens_per_second
        * inputs.replicas
        * (inputs.target_utilization / 100)
        * SECONDS_PER_DAY
        * duty
        / inputs.output_tokens_request
    )
    requests = inputs.requests_per_day * inputs.active_days
    output_tokens = requests * inputs.output_tokens_request
    return HostingEstimate(
        weight_memory_gb=weight_memory,
        required_memory_gb=required_memory,
        nodes_per_replica=nodes_per_replica,
        total_nodes=total_nodes,
        total_gpus=total_nodes * node.gpu_count,
        compute_monthly_usd=compute_monthly,
        control_monthly_usd=control_monthly,
        platform_monthly_usd=inputs.platform_monthly_usd,
        total_monthly_usd=total_monthly,
        capacity_tokens_month=capacity,
        capacity_requests_day=capacity_requests_day,
        requests_month=requests,
        input_tokens_month=requests * inputs.input_tokens_request,
        output_tokens_month=output_tokens,
        demand_capacity_pct=output_tokens / capacity * 100,
        per_thousand_requests_usd=total_monthly / requests * 1000,
        demand_fits=output_tokens <= capacity,
    )


def current_api_baselines(
    now: datetime,
    inputs: HostingInputs,
) -> tuple[APIBaseline, ...]:
    current_date = _utc_date(now)
    rows: list[APIBaseline] = []
    for baseline in API_BASELINES:
        row = baseline
        if row.valid_through and current_date > row.valid_through:
            row = replace(
                row,
                input_per_million=row.input_per_million * 2,
                output_per_million=row.output_per_million * 2,
                cache_read_per_million=row.cache_read_per_million * 2,
                cache_storage_per_million_hour=row.cache_storage_per_million_hour * 2,
                note="The announced January 2027 rates are applied. This snapshot needs a fresh source check.",
            )
        if row.name == "GPT-6 Astra" and inputs.input_tokens_request > 272_000:
            row = replace(
                row,
                input_per_million=20,
                output_per_million=75,
                cache_read_per_million=2,
                cache_write_per_million=25,
            )
        rows.append(row)
    return tuple(rows)


def api_monthly_cost(
    inputs: HostingInputs,
    baseline: APIBaseline,
    requests: float,
) -> tuple[float, float]:
    input_cost = inputs.input_tokens_request * requests * baseline.input_per_million
    output_cost = inputs.output_tokens_request * requests * baseline.output_per_million
    if inputs.api_mode is APIMode.BATCH:
        return (input_cost + output_cost) / 2_000_000, 0
    overhead = 0.0
    if inputs.api_mode is APIMode.CACHED:
        prefix = inputs.cache_prefix_tokens
        if baseline.cache_minimum <= prefix <= inputs.input_tokens_request:
            # A partially filled final group still incurs a complete warm-up.
            writes = min(requests, ceil(requests / inputs.cache_requests))
            reads = requests - writes
            input_cost = (inputs.input_tokens_request - prefix) * requests * baseline.input_per_million
            if baseline.cache_storage_per_million_hour > 0:
                reads = requests
                overhead = writes * prefix * baseline.cache_storage_per_million_hour / 12
            else:
                overhead = writes * prefix * baseline.cache_write_per_million
            input_cost += reads * prefix * baseline.cache_read_per_million + overhead
    return (input_cost + output_cost) / 1_000_000, overhead / 1_000_000


def _api_mode_note(inputs: HostingInputs, baseline: APIBaseline) -> str:
    if inputs.api_mode is APIMode.BATCH:
        return (
            "Batch: 50% off input and output. Asynchronous jobs, up to 24 hours; "
            "unsuitable for live chat. No cache discount combined here."
        )
    if inputs.api_mode is APIMode.CACHED:
        if not (baseline.cache_minimum <= inputs.cache_prefix_tokens <= inputs.input_tokens_request):
            return (
                "Standard rates applied: caching needs at least "
                f"{format_decimal(baseline.cache_minimum, 0)} shared prefix tokens, "
                "within the request's input budget."
            )
        if baseline.cache_storage_per_million_hour > 0:
            return (
                f"Explicit Gemini cache: {format_usd2(baseline.cache_read_per_million)}/M "
                f"cached input + {format_usd2(baseline.cache_storage_per_million_hour)}/M "
                "token-hours stored; five-minute storage charged for every group. Use "
                "GenerateContent, not the Interactions-only implicit cache."
            )
        return (
            f"Cache: {format_usd2(baseline.cache_write_per_million)}/M prefix tokens "
            f"on the first call, {format_usd2(baseline.cache_read_per_million)}/M on "
            "reuse. Calls must share an exact prefix within five minutes; Astra retains "
            "it for at least 30 minutes."
        )
    return "Standard uncached text rates. Immediate requests; no batch or cache discount assumed."


def _compare_apis(
    inputs: HostingInputs,
    estimate: HostingEstimate,
    baselines: tuple[APIBaseline, ...],
) -> tuple[APIComparison, ...]:
    rows: list[APIComparison] = []
    for baseline in baselines:
        monthly, overhead = api_monthly_cost(inputs, baseline, estimate.requests_month)
        # Cache groups make the bill piecewise linear; find the first whole request.
        low, high = 0, 1
        while api_monthly_cost(inputs, baseline, high)[0] < estimate.total_monthly_usd:
            high *= 2
        while low + 1 < high:
            middle = low + (high - low) // 2
            if api_monthly_cost(inputs, baseline, middle)[0] >= estimate.total_monthly_usd:
                high = middle
            else:
                low = middle
        rows.append(
            APIComparison(
                baseline=baseline,
                monthly_usd=monthly,
                cache_overhead_usd=overhead,
                per_thousand_requests_usd=monthly / estimate.requests_month * 1000,
                break_even_requests=float(high),
                break_even_fits=(high * inputs.output_tokens_request <= estimate.capacity_tokens_month),
                mode_note=_api_mode_note(inputs, baseline),
            ),
        )
    return tuple(rows)


def _hosting_tasks(
    inputs: HostingInputs,
    estimate: HostingEstimate,
    baselines: tuple[APIBaseline, ...],
) -> tuple[TaskComparison, ...]:
    rows: list[TaskComparison] = []
    for index, quality in enumerate(inputs.quality):
        requests = inputs.tasks_per_month * quality.calls_per_task
        accepted = inputs.tasks_per_month * quality.acceptance_percent / 100
        model_usd = estimate.total_monthly_usd
        fits = requests * inputs.output_tokens_request <= estimate.capacity_tokens_month
        name = "Your GKE fleet"
        if index > 0:
            name = baselines[index - 1].name
            model_usd = api_monthly_cost(inputs, baselines[index - 1], requests)[0]
            fits = True
        review_usd = inputs.tasks_per_month * quality.review_minutes / 60 * inputs.review_hourly_usd
        rows.append(
            TaskComparison(
                id=f"quality-{index}",
                name=name,
                quality=quality,
                requests=requests,
                accepted=accepted,
                model_usd=model_usd,
                review_usd=review_usd,
                per_accepted_usd=(model_usd + review_usd) / accepted if accepted else 0,
                fits=fits,
            ),
        )
    return tuple(rows)


def _hosting_decision(
    model: FrontierModel,
    node: GKENodePool,
    estimate: HostingEstimate,
) -> str:
    if model.license_class != "Permissive":
        return "Review commercial terms"
    if estimate.nodes_per_replica > 1:
        return "Validate multi-node serving"
    if estimate.required_memory_gb < node.hbm_gb * 0.25:
        return "Right-size the node pool"
    return "Pilot on this topology"


def _demand_label(inputs: HostingInputs) -> str:
    for preset in DEMAND_PRESETS:
        if (
            inputs.requests_per_day == preset.requests_per_day
            and inputs.active_days == preset.active_days
            and inputs.input_tokens_request == preset.input_tokens
            and inputs.output_tokens_request == preset.output_tokens
        ):
            return preset.name
    return "Custom demand"


def _hosting_latency(inputs: HostingInputs) -> tuple[str, str]:
    if (
        inputs.measured_concurrency < inputs.concurrency
        or inputs.measured_first_token == 0
        or inputs.measured_completion == 0
    ):
        return (
            "Responsiveness is still unproved",
            "Record p95 first-token and completion times at your target concurrency using this configuration.",
        )
    if inputs.measured_first_token > inputs.target_first_token or inputs.measured_completion > inputs.target_completion:
        return (
            "The recorded pilot misses a latency target",
            "Revisit batching, replicas, or model size, then measure again.",
        )
    return (
        "The recorded pilot meets your latency targets",
        "Both p95 measurements meet your targets at the recorded concurrency; production performance remains unproved.",
    )


def _float_for_url(value: float) -> str:
    if value.is_integer():
        return str(int(value))
    # repr is the shortest round-tripping form; Decimal expands its exponent
    # because Go's strconv.FormatFloat with the `f` verb never emits one.
    return format(Decimal(repr(value)), "f")


def hosting_url(inputs: HostingInputs) -> str:
    values = {
        "model": inputs.model_id,
        "node": inputs.node_pool_id,
        "quant": inputs.quantization_id,
        "api-mode": inputs.api_mode.value,
        "replicas": str(inputs.replicas),
        "cache-requests": str(inputs.cache_requests),
        "concurrency": str(inputs.concurrency),
        "measured-concurrency": str(inputs.measured_concurrency),
        "duty": _float_for_url(inputs.duty_cycle_percent),
        "overhead": _float_for_url(inputs.memory_overhead_pct),
        "throughput": _float_for_url(inputs.tokens_per_second),
        "utilization": _float_for_url(inputs.target_utilization),
        "tokens": _float_for_url(inputs.output_tokens_request),
        "input-tokens": _float_for_url(inputs.input_tokens_request),
        "requests": _float_for_url(inputs.requests_per_day),
        "days": _float_for_url(inputs.active_days),
        "platform": _float_for_url(inputs.platform_monthly_usd),
        "cache-prefix": _float_for_url(inputs.cache_prefix_tokens),
        "target-first": _float_for_url(inputs.target_first_token),
        "target-complete": _float_for_url(inputs.target_completion),
        "measured-first": _float_for_url(inputs.measured_first_token),
        "measured-complete": _float_for_url(inputs.measured_completion),
        "tasks": _float_for_url(inputs.tasks_per_month),
        "review-rate": _float_for_url(inputs.review_hourly_usd),
    }
    if inputs.quality_enabled:
        values["quality"] = "on"
    for index, quality in enumerate(inputs.quality):
        values[f"quality-{index}-acceptance"] = _float_for_url(
            quality.acceptance_percent,
        )
        values[f"quality-{index}-calls"] = _float_for_url(quality.calls_per_task)
        values[f"quality-{index}-review"] = _float_for_url(quality.review_minutes)
    return "/sites/llm-self-hosting/?" + urlencode(sorted(values.items()))


def _plot_coordinate(value: float) -> str:
    return f"{value:.2f}"


def _go_log_positive(value: float) -> float:
    """Match Go's math.Log for the positive, finite chart domain."""
    if not isfinite(value) or value <= 0:
        msg = "Go-compatible logarithm requires a positive finite value"
        raise ValueError(msg)
    l1, l2, l3, l4, l5, l6, l7 = _GO_LOG_COEFFICIENTS
    fraction, exponent = frexp(value)
    if fraction < sqrt(2) / 2:
        fraction *= 2
        exponent -= 1
    reduced = fraction - 1
    ratio = reduced / (2 + reduced)
    ratio2 = ratio * ratio
    ratio4 = ratio2 * ratio2
    odd = ratio2 * (l1 + ratio4 * (l3 + ratio4 * (l5 + ratio4 * l7)))
    even = ratio4 * (l2 + ratio4 * (l4 + ratio4 * l6))
    remainder = odd + even
    half_square = 0.5 * reduced * reduced
    scale = float(exponent)
    return scale * _GO_LN2_HI - ((half_square - (ratio * (half_square + remainder) + scale * _GO_LN2_LO)) - reduced)


def _go_exp(value: float) -> float:
    """Match Go's amd64/FMA math.Exp for the bounded chart exponent."""
    exponent = round(_GO_AMD64_LOG2E * value)
    scale = float(exponent)
    reduced = fma(-_GO_AMD64_LN2_UPPER, scale, value)
    reduced = fma(-_GO_AMD64_LN2_LOWER, scale, reduced) * 0.0625
    polynomial = _GO_AMD64_EXP_COEFFICIENTS[0]
    for coefficient in _GO_AMD64_EXP_COEFFICIENTS[1:]:
        polynomial = fma(polynomial, reduced, coefficient)
    result = reduced * polynomial
    for _ in range(3):
        result *= 2 + result
    result = fma(result, 2 + result, 1)
    return ldexp(result, exponent)


def _go_pow_unit(base: float, exponent: float) -> float:
    """Match Go's math.Pow for a positive base and exponent in [0, 1]."""
    if not isfinite(base) or base <= 0 or not 0 <= exponent <= 1:
        msg = "Go-compatible power requires a positive finite base and a unit exponent"
        raise ValueError(msg)
    if exponent == 0:
        return 1
    if exponent == 1:
        return base
    if exponent == 0.5:
        return sqrt(base)

    integer = 0
    fractional = exponent
    if fractional > 0.5:
        fractional -= 1
        integer = 1
    result = _go_exp(fractional * _go_log_positive(base))
    if integer:
        fraction, scale = frexp(base)
        result *= fraction
        return ldexp(result, scale)
    return result


def _hosting_cost_plot(
    inputs: HostingInputs,
    estimate: HostingEstimate,
    apis: tuple[APIComparison, ...],
) -> CostPlot:
    capacity = estimate.capacity_tokens_month / inputs.output_tokens_request
    max_break_even = max(api.break_even_requests for api in apis)
    max_daily = min(
        10_000_000,
        max(
            inputs.requests_per_day * 4,
            max_break_even / inputs.active_days * 1.2,
            capacity / inputs.active_days * 1.2,
        ),
    )
    # Log axes keep small-team demand and million-request crossings legible.
    max_daily = max(10, max_daily)

    def x(requests: float) -> str:
        return _plot_coordinate(
            130 + log10(max(1, requests / inputs.active_days)) / log10(max_daily) * 590,
        )

    max_cost = max(
        estimate.total_monthly_usd,
        *(api_monthly_cost(inputs, api.baseline, max_daily * inputs.active_days)[0] for api in apis),
    )

    def y(cost: float) -> str:
        return _plot_coordinate(300 - log10(1 + cost) / log10(1 + max_cost) * 260)

    capacity_x = ""
    capacity_width = ""
    if inputs.active_days <= capacity <= max_daily * inputs.active_days:
        capacity_x = x(capacity)
        capacity_width = _plot_coordinate(
            590 - log10(max(1, capacity / inputs.active_days)) / log10(max_daily) * 590,
        )

    daily_values = [inputs.requests_per_day]
    daily_values.extend(_go_pow_unit(max_daily, index / 60) for index in range(61))
    break_evens: list[PlotTick] = []
    for api in apis:
        if inputs.active_days <= api.break_even_requests <= max_daily * inputs.active_days:
            daily_values.append(api.break_even_requests / inputs.active_days)
            break_evens.append(
                PlotTick(
                    x(api.break_even_requests),
                    f"{api.baseline.name}: {format_decimal(api.break_even_requests, 0)} requests/month",
                ),
            )

    paths: list[list[str]] = [[], [], [], []]
    frames: list[CostFrame] = []
    selected = 0
    for index, daily in enumerate(sorted(set(daily_values))):
        scenario = replace(inputs, requests_per_day=daily)
        requests = daily * inputs.active_days
        label = f"{format_decimal(requests, 0)} requests/month"
        fit = "within modeled capacity" if requests <= capacity else "beyond this fleet's capacity"
        summary = f"{label} · {fit}. GKE fleet {format_usd2(estimate.total_monthly_usd)}"
        paths[0].append(f"{x(requests)},{y(estimate.total_monthly_usd)}")
        for api_index, api in enumerate(apis):
            total = api_monthly_cost(inputs, api.baseline, requests)[0]
            summary += f" · {api.baseline.name} {format_usd2(total)}"
            paths[api_index + 1].append(f"{x(requests)},{y(total)}")
        frames.append(
            CostFrame(
                x=x(requests),
                label=label,
                summary=summary + " per month.",
                url=hosting_url(scenario),
                requests=requests,
            ),
        )
        if daily == inputs.requests_per_day:
            selected = index

    names = ("GKE fleet", *(api.baseline.name for api in apis))
    lines = tuple(PlotLine(name=name, points=" ".join(paths[index])) for index, name in enumerate(names))
    x_ticks: list[PlotTick] = []
    y_ticks: list[PlotTick] = []
    for index in range(5):
        requests = max_daily ** (index / 4) * inputs.active_days
        x_ticks.append(PlotTick(x(requests), format_number(requests)))
        cost = (1 + max_cost) ** (index / 4) - 1
        y_ticks.append(PlotTick(y(cost), _chart_usd(cost)))
    return CostPlot(
        capacity_x=capacity_x,
        capacity_width=capacity_width,
        capacity_label=f"{format_decimal(capacity, 0)} requests/month",
        fleet_y=y(estimate.total_monthly_usd),
        lines=lines,
        frames=tuple(frames),
        x_ticks=tuple(x_ticks),
        y_ticks=tuple(y_ticks),
        break_evens=tuple(break_evens),
        selected=selected,
    )


def _hosting_sensitivity(
    inputs: HostingInputs,
    baselines: tuple[APIBaseline, ...],
) -> tuple[SensitivityRow, ...]:
    labels = ("Lower demand · ½×", "Your demand · 1×", "Higher demand · 2×")
    rows: list[SensitivityRow] = []
    for row_index, demand in enumerate((0.5, 1, 2)):
        cells: list[SensitivityCell] = []
        for speed in (0.5, 1, 2):
            scenario = replace(
                inputs,
                requests_per_day=min(10_000_000, max(1, inputs.requests_per_day * demand)),
                tokens_per_second=min(1_000_000, max(0.1, inputs.tokens_per_second * speed)),
            )
            estimate = estimate_hosting(
                _find_model(inputs.model_id),
                _find_node_pool(inputs.node_pool_id),
                _find_quantization(inputs.quantization_id),
                scenario,
            )
            cheapest = min(api_monthly_cost(scenario, baseline, estimate.requests_month)[0] for baseline in baselines)
            verdict = "API costs less"
            if estimate.total_monthly_usd <= cheapest:
                verdict = "Fleet has a cost case"
            if not estimate.demand_fits:
                verdict = "Fleet too small"
            cells.append(
                SensitivityCell(
                    url=hosting_url(scenario),
                    verdict=verdict,
                    inputs=scenario,
                    capacity_pct=estimate.demand_capacity_pct,
                    cheapest_api_usd=cheapest,
                    fits=estimate.demand_fits,
                ),
            )
        rows.append(SensitivityRow(labels[row_index], tuple(cells)))
    return tuple(rows)


def _utc_date(now: datetime) -> str:
    if now.tzinfo is None:
        now = now.replace(tzinfo=UTC)
    return now.astimezone(UTC).date().isoformat()


def build_llm_self_hosting_view(
    query: Query | None = None,
    *,
    now: datetime | None = None,
) -> LLMSelfHostingView:
    query = query or {}
    now = now or datetime.now(UTC)
    inputs, validation = _parse_inputs(query)
    model = _find_model(inputs.model_id)
    node = _find_node_pool(inputs.node_pool_id)
    quantization = _find_quantization(inputs.quantization_id)
    estimate = estimate_hosting(model, node, quantization, inputs)
    baselines = current_api_baselines(now, inputs)
    review_date = _utc_date(now)
    apis = tuple(
        replace(
            comparison,
            needs_review=review_date >= comparison.baseline.review_on,
            freshness=(
                f"Verified {comparison.baseline.verified_on} · review by "
                f"{comparison.baseline.review_on}"
                + (
                    " · review overdue: check the linked price before deciding"
                    if review_date >= comparison.baseline.review_on
                    else ""
                )
            ),
        )
        for comparison in _compare_apis(inputs, estimate, baselines)
    )
    latency_title, latency_detail = _hosting_latency(inputs)
    precisions = tuple(PrecisionComparison(item, estimate_hosting(model, node, item, inputs)) for item in QUANTIZATIONS)
    comparisons: list[ModelComparison] = []
    for candidate in FRONTIER_MODELS:
        candidate_estimate = estimate_hosting(candidate, node, quantization, inputs)
        comparisons.append(
            ModelComparison(
                candidate,
                candidate_estimate,
                _hosting_decision(candidate, node, candidate_estimate),
            ),
        )
    return LLMSelfHostingView(
        inputs=inputs,
        models=FRONTIER_MODELS,
        node_pools=GKE_NODE_POOLS,
        quantizations=QUANTIZATIONS,
        selected_model=model,
        selected_node=node,
        selected_quant=quantization,
        estimate=estimate,
        comparison=tuple(comparisons),
        validation=validation,
        snapshot_date=MODEL_SNAPSHOT,
        index_version=INDEX_VERSION,
        presets=DEMAND_PRESETS,
        apis=apis,
        precisions=precisions,
        demand_label=_demand_label(inputs),
        cost_plot=_hosting_cost_plot(inputs, estimate, apis),
        sensitivity=_hosting_sensitivity(inputs, baselines),
        tasks=_hosting_tasks(inputs, estimate, baselines),
        latency_title=latency_title,
        latency_detail=latency_detail,
        model_source_url=MODEL_SOURCE_URL,
        gke_source_url=GKE_SOURCE_URL,
        price_source_url=PRICE_SOURCE_URL,
    )


def _round_away_from_zero(value: float) -> float:
    return float(floor(value + 0.5) if value >= 0 else -floor(-value + 0.5))


def format_decimal(value: float, digits: int) -> str:
    scale = 10**digits
    rounded = _round_away_from_zero(value * scale) / scale
    return f"{rounded:,.{digits}f}"


def format_usd(value: float) -> str:
    return "$" + format_decimal(value, 0)


def format_usd2(value: float) -> str:
    return "$" + format_decimal(value, 2)


def format_number(value: float) -> str:
    if value >= 1e12:
        return f"{value / 1e12:.2f}T"
    if value >= 1e9:
        return f"{value / 1e9:.2f}B"
    if value >= 1e6:
        return f"{value / 1e6:.2f}M"
    if value >= 1e3:
        return f"{value / 1e3:.1f}k"
    return f"{value:.0f}"


def format_count(value: int, noun: str) -> str:
    """Format a whole quantity with a simple English plural."""
    suffix = "" if value == 1 else "s"
    return f"{format_decimal(float(value), 0)} {noun}{suffix}"


def task_cost_max(rows: Sequence[TaskComparison]) -> float:
    """Return the non-zero scale used by the accepted-task comparison bars."""
    return max((row.per_accepted_usd for row in rows if row.fits), default=0.01)


def hosting_decision_title(view: LLMSelfHostingView) -> str:
    """Summarize the immediate economic conclusion without hiding capacity."""
    if not view.estimate.demand_fits:
        return "This fleet cannot cover the modeled demand"
    if min(row.monthly_usd for row in view.apis) < view.estimate.total_monthly_usd:
        return "Start with an API on cost grounds"
    return "Self-hosting has a cost case to test"


def hosting_decision_copy(view: LLMSelfHostingView) -> str:
    """Explain the capacity and cost conclusion in decision-ready language."""
    if not view.estimate.demand_fits:
        return (
            "Do not treat the current fleet bill as a quote for all this work. Increase replicas, measure a faster "
            "configuration, or reduce demand, then recalculate. A monthly average cannot establish peak-time capacity."
        )
    cheapest = min(view.apis, key=lambda row: row.monthly_usd)
    if cheapest.monthly_usd < view.estimate.total_monthly_usd:
        return (
            f"{cheapest.baseline.name} is {format_usd2(cheapest.monthly_usd)}/month for this token mix, versus "
            f"{format_usd2(view.estimate.total_monthly_usd)} for your fleet. Self-hosting needs enough value from "
            "control, residency, customization, or avoided quality failures to cover the difference. Compare task "
            "success before choosing."
        )
    return (
        "The modeled fleet bill is below these API baselines at your demand. This is a candidate for a pilot: verify "
        "quality, sustained throughput, memory, model terms, and an operating owner before committing capacity."
    )


def _chart_usd(value: float) -> str:
    for suffix, scale in (("T", 1e12), ("B", 1e9), ("M", 1e6), ("k", 1e3)):
        if value >= scale:
            if value / scale < 10:
                return f"${value / scale:.1f}{suffix}"
            return f"${value / scale:.0f}{suffix}"
    return format_usd(value)
