from __future__ import annotations

from .models import (
    APIBaseline,
    APIMode,
    BillingPlan,
    DemandPreset,
    FrontierModel,
    GKENodePool,
    HostingInputs,
    NodePrice,
    Quantization,
    TaskQuality,
)

# These immutable source snapshots preserve the published typography verbatim.
# ruff: noqa: RUF001


MODEL_SNAPSHOT = "2026-09-07"
INDEX_VERSION = "4.2"
MODEL_SOURCE_URL = "https://artificialanalysis.ai/models"
GKE_SOURCE_URL = "https://cloud.google.com/kubernetes-engine/pricing"
PRICE_SOURCE_URL = "https://cloud.google.com/products/compute/pricing/accelerator-optimized"

# Static minimums use 4-bit weights plus 25% reserve: fewest hosts, then
# smallest aggregate VRAM from the listed machines; multi-host uses A3/A4.
FRONTIER_MODELS = (
    FrontierModel(
        "kimi-k3",
        1,
        "Kimi K3 (max)",
        "Moonshot AI",
        50.2337,
        2800,
        104,
        1_048_576,
        "Kimi K3 License",
        "Commercial license",
        "https://artificialanalysis.ai/models/kimi-k3",
        "https://huggingface.co/moonshotai/Kimi-K3",
        "a3-ultra",
        2,
    ),
    FrontierModel(
        "glm-5-3",
        2,
        "GLM-5.3 (max)",
        "Z AI",
        48.5840,
        753,
        40,
        1_000_000,
        "GLM-5.3 License",
        "Commercial license",
        "https://artificialanalysis.ai/models/glm-5-3",
        "https://huggingface.co/zai-org/GLM-5.3",
        "a3-high",
        1,
    ),
    FrontierModel(
        "qwen3-8-2-4t-a95b",
        3,
        "Qwen3.8 2.4T A95B",
        "Alibaba",
        46.7403,
        2400,
        95,
        983_616,
        "Qwen3.8-Max License",
        "Commercial license",
        "https://artificialanalysis.ai/models/qwen3-8-2-4t-a95b",
        "https://huggingface.co/Qwen/Qwen3.8-2.4T-A95B",
        "a3-ultra",
        2,
    ),
    FrontierModel(
        "glm-5-3-flash",
        4,
        "GLM-5.3-Flash",
        "Z AI",
        46.2237,
        320,
        18,
        1_000_000,
        "MIT",
        "Permissive",
        "https://artificialanalysis.ai/models/glm-5-3-flash",
        "https://huggingface.co/zai-org/GLM-5.3-Flash",
        "a3-high",
        1,
    ),
    FrontierModel(
        "deepseek-v4-pro",
        5,
        "DeepSeek V4 Pro 0813 (max)",
        "DeepSeek",
        42.1133,
        1600,
        49,
        1_000_000,
        "MIT",
        "Permissive",
        "https://artificialanalysis.ai/models/deepseek-v4-pro",
        "https://huggingface.co/deepseek-ai/DeepSeek-V4-Pro-0813",
        "a3-ultra",
        1,
    ),
    FrontierModel(
        "qwen3-8-27b",
        6,
        "Qwen3.8 27B (xhigh)",
        "Alibaba",
        41.4059,
        27,
        27,
        256_000,
        "Apache 2.0",
        "Permissive",
        "https://artificialanalysis.ai/models/qwen3-8-27b",
        "https://huggingface.co/Qwen/Qwen3.8-27B",
        "g2-standard-12",
        1,
    ),
    FrontierModel(
        "k2-horizon-375b-a23b",
        7,
        "K2 Horizon 375B A23B",
        "MBZUAI",
        37.7507,
        375,
        23,
        524_288,
        "Apache 2.0",
        "Permissive",
        "https://artificialanalysis.ai/models/k2-horizon-375b-a23b",
        "https://huggingface.co/IFM/K2-Horizon-375B-A23B",
        "a3-high",
        1,
    ),
    FrontierModel(
        "minimax-m3",
        8,
        "MiniMax-M3",
        "MiniMax",
        35.7477,
        428,
        23,
        1_000_000,
        "MiniMax Community License",
        "Commercial license",
        "https://artificialanalysis.ai/models/minimax-m3",
        "https://huggingface.co/MiniMaxAI/MiniMax-M3",
        "a3-high",
        1,
    ),
    FrontierModel(
        "inkling",
        9,
        "Inkling (xhigh)",
        "Thinking Machines",
        32.1665,
        975,
        41,
        1_000_000,
        "Apache 2.0",
        "Permissive",
        "https://artificialanalysis.ai/models/inkling",
        "https://huggingface.co/thinkingmachines/Inkling",
        "a3-high",
        1,
    ),
    FrontierModel(
        "muse-glimmer",
        10,
        "Muse Glimmer (high)",
        "Meta",
        24.3773,
        30,
        30,
        131_072,
        "Apache 2.0",
        "Permissive",
        "https://artificialanalysis.ai/models/muse-glimmer",
        "https://huggingface.co/meta-models/Muse-Glimmer-30B",
        "g2-standard-12",
        1,
    ),
)

# Full-machine USD prices, including attached GPUs and bundled host resources.
# Resource CUD columns are used explicitly; flexible CUDs are not GPU CUDs.
GKE_NODE_POOLS = (
    GKENodePool(
        "g2-standard-12",
        "G2 · 1× L4 · 24 GB",
        "1× NVIDIA L4",
        1,
        24,
        (
            NodePrice(BillingPlan.ON_DEMAND, "On-demand", 1.000416348),
            NodePrice(BillingPlan.CUD_1Y, "1-year resource CUD", 0.630262303),
            NodePrice(BillingPlan.CUD_3Y, "3-year resource CUD", 0.450187356),
        ),
        "48 GiB host RAM. Small-model inference; validate checkpoint loading, runtime support, and KV cache.",
    ),
    GKENodePool(
        "g4-standard-48",
        "G4 · 1× RTX PRO 6000 · 96 GB",
        "1× NVIDIA RTX PRO 6000 Blackwell Server Edition",
        1,
        96,
        (
            NodePrice(BillingPlan.ON_DEMAND, "On-demand", 4.49993),
            NodePrice(BillingPlan.CUD_1Y, "1-year resource CUD", 3.105),
            NodePrice(BillingPlan.CUD_3Y, "3-year resource CUD", 1.97945),
        ),
        "180 GiB host RAM. GCP Server Edition; verify GKE version, drivers, regional quota, and capacity.",
    ),
    GKENodePool(
        "a2-ultra-1g",
        "A2 Ultra · 1× A100 · 80 GB",
        "1× NVIDIA A100 80GB",
        1,
        80,
        (
            NodePrice(BillingPlan.ON_DEMAND, "On-demand", 5.06879789),
            NodePrice(BillingPlan.CUD_1Y, "1-year resource CUD", 4.199690411),
            NodePrice(BillingPlan.CUD_3Y, "3-year resource CUD", 3.499997559),
        ),
        "Best used for models that fit on one node; inter-node serving needs separate validation.",
    ),
    GKENodePool(
        "a3-high",
        "A3 High · 8× H100 · 640 GB",
        "8× NVIDIA H100",
        8,
        640,
        (
            NodePrice(BillingPlan.ON_DEMAND, "On-demand", 88.490000119),
            NodePrice(BillingPlan.CUD_1Y, "1-year resource CUD", 61.383674231),
            NodePrice(BillingPlan.CUD_3Y, "3-year resource CUD", 38.864383195),
        ),
        "Validate regional stock, quota, and multi-host networking.",
        multi_host=True,
    ),
    GKENodePool(
        "a3-ultra",
        "A3 Ultra · 8× H200 · 1,128 GB",
        "8× NVIDIA H200",
        8,
        1128,
        (
            NodePrice(BillingPlan.ON_DEMAND, "On-demand", 84.806908493),
            NodePrice(BillingPlan.CUD_1Y, "1-year resource CUD", 58.471933151),
            NodePrice(BillingPlan.CUD_3Y, "3-year resource CUD", 37.208420822),
        ),
        "Validate regional stock, quota, and RDMA topology.",
        multi_host=True,
    ),
    GKENodePool(
        "a4",
        "A4 · 8× B200 · 1,440 GB",
        "8× NVIDIA B200",
        8,
        1440,
        (
            NodePrice(BillingPlan.FLEX, "DWS Flex-start", 64.44),
            NodePrice(BillingPlan.CUD_1Y, "1-year resource CUD", 88.9272),
            NodePrice(BillingPlan.CUD_3Y, "3-year resource CUD", 56.7072),
        ),
        "No on-demand list rate. Flex-start suits queued jobs; continuous serving needs reserved capacity.",
        multi_host=True,
    ),
)

QUANTIZATIONS = (
    Quantization(
        "fp4",
        "4-bit · prioritize memory savings",
        0.5,
        "¼ of 16-bit weight memory. Validate reasoning, tool use, and accuracy before accepting the quality trade-off.",
    ),
    Quantization(
        "fp8",
        "8-bit · balanced starting experiment",
        1,
        "½ of 16-bit weight memory. A practical first compression test with a supported checkpoint and runtime.",
    ),
    Quantization(
        "fp16",
        "16-bit · precision reference",
        2,
        "Full weight memory as a precision reference. Expanding quantized weights cannot recover lost quality.",
    ),
)

DEMAND_PRESETS = (
    DemandPreset(
        "single-job",
        "Single job",
        "Process 100 documents once: 100 requests on one day, 4,000 input / 1,000 output tokens each.",
        100,
        1,
        4000,
        1000,
    ),
    DemandPreset(
        "small-team",
        "Small team · 5–10 people",
        "Example: 8 people × 20 requests × 22 workdays, 2,000 input / 600 output tokens each.",
        160,
        22,
        2000,
        600,
    ),
    DemandPreset(
        "department",
        "Department · 50 people",
        "50 people × 40 requests × 22 workdays, 4,000 input / 1,000 output tokens each.",
        2000,
        22,
        4000,
        1000,
    ),
    DemandPreset(
        "service",
        "Busy customer service",
        "100,000 requests per day × 30 days, 1,000 input / 300 output tokens each. Test peak traffic too.",
        100_000,
        30,
        1000,
        300,
    ),
)

API_BASELINES = (
    APIBaseline(
        "Gemini 3.8 Flash",
        0.75,
        3.75,
        0.075,
        0,
        0.5,
        4096,
        "https://ai.google.dev/gemini-api/docs/pricing#gemini-3.8-flash",
        "https://ai.google.dev/gemini-api/docs/generate-content/caching",
        MODEL_SNAPSHOT,
        "2026-10-07",
        "2026-12-31",
        "Introductory rates through Dec 31, 2026; input, output, cache reads, and storage double on Jan 1, 2027.",
    ),
    APIBaseline(
        "Claude Sonnet 5",
        2,
        10,
        0.2,
        2.5,
        0,
        1024,
        "https://platform.claude.com/docs/en/about-claude/pricing",
        "https://platform.claude.com/docs/en/build-with-claude/prompt-caching",
        MODEL_SNAPSHOT,
        "2026-10-07",
        "",
        "$2 / $10 is standard pricing; the previously announced September increase was canceled. No announced end date.",
    ),
    APIBaseline(
        "GPT-6 Astra",
        10,
        50,
        1,
        12.5,
        0,
        1024,
        "https://developers.openai.com/api/docs/models/gpt-6-astra",
        "https://developers.openai.com/api/docs/guides/prompt-caching",
        MODEL_SNAPSHOT,
        "2026-10-07",
        "",
        "OpenAI's published Astra name. Above 272,000 input tokens, full-request rates rise to $20 input / $75 output per million. No announced end date.",
    ),
)

DEFAULT_HOSTING_INPUTS = HostingInputs(
    model_id="qwen3-8-27b",
    node_pool_id="a2-ultra-1g",
    quantization_id="fp8",
    replicas=1,
    duty_cycle_percent=100,
    memory_overhead_pct=15,
    tokens_per_second=100,
    target_utilization=65,
    output_tokens_request=600,
    input_tokens_request=2000,
    requests_per_day=160,
    active_days=22,
    platform_monthly_usd=1000,
    api_mode=APIMode.STANDARD,
    cache_prefix_tokens=1024,
    cache_requests=20,
    concurrency=8,
    target_first_token=2,
    target_completion=30,
    measured_concurrency=0,
    measured_first_token=0,
    measured_completion=0,
    tasks_per_month=1000,
    review_hourly_usd=40,
    quality=(
        TaskQuality(90, 1, 1),
        TaskQuality(90, 1, 1),
        TaskQuality(90, 1, 1),
        TaskQuality(90, 1, 1),
    ),
    quality_enabled=False,
)
